### PR TITLE
traverse the entire tree

### PR DESCRIPTION
**Pull request by szvsw**

### CODE REVIEW

**Comment by szvsw** [comment]
@samuelduchesne I don't have write access to `archetypal` so just forked it here -

Something that I just noticed, which maybe is not a problem but also maybe worth mentioning:

When the `traverse` is used to reset ids with `self.id = None`, it only resets IDs of entities which are actually a child of a template; if an entity is not in any template's tree, it does not get its ID reset:

```
"GasMaterials": [
        {
            "$id": "1",
            "Category": "Gases",
            "Type": "AIR",
            "Conductivity": 0,
            "Cost": 0,
            "Density": 0,
            "EmbodiedCarbon": 0,
            "EmbodiedEnergy": 0,
            "SubstitutionRatePattern": [],
            "SubstitutionTimestep": 0,
            "TransportCarbon": 0,
            "TransportDistance": 0,
            "TransportEnergy": 0,
            "Comments": null,
            "DataSource": null,
            "Name": "$AIR"
        },
        {
            "$id": "140435951990528",
            "Category": "Gases",
            "Type": "AIR",
            "Conductivity": 0,
            "Cost": 0,
            "Density": 0,
            "EmbodiedCarbon": 0,
            "EmbodiedEnergy": 0,
            "SubstitutionRatePattern": [],
            "SubstitutionTimestep": 0,
            "TransportCarbon": 0,
            "TransportDistance": 0,
            "TransportEnergy": 0,
            "Comments": null,
            "DataSource": null,
            "Name": "$AIR_$1"
        },
        {
            "$id": "2",
            "Category": "Gases",
            "Type": "ARGON",
            "Conductivity": 0,
            "Cost": 0,
            "Density": 0,
            "EmbodiedCarbon": 0,
            "EmbodiedEnergy": 0,
            "SubstitutionRatePattern": [],
            "SubstitutionTimestep": 0,
            "TransportCarbon": 0,
            "TransportDistance": 0,
            "TransportEnergy": 0,
            "Comments": null,
            "DataSource": null,
            "Name": "$ARGON"
        },
        {
            "$id": "2",
            "Category": "Gases",
            "Type": "ARGON",
            "Conductivity": 0,
            "Cost": 0,
            "Density": 0,
            "EmbodiedCarbon": 0,
            "EmbodiedEnergy": 0,
            "SubstitutionRatePattern": [],
            "SubstitutionTimestep": 0,
            "TransportCarbon": 0,
            "TransportDistance": 0,
            "TransportEnergy": 0,
            "Comments": null,
            "DataSource": null,
            "Name": "$ARGON_$1"
        },
...
```

`AIR` is used in a template, but `ARGON` is not - it is used in a few `WindowConstruction`s (`B_Dbl_Arg_Cl` and `B_Dbl_Arg_Le`), but those constructions are not used in any templates.

This seems like it is then constructing an invalid template library, as you get duplicated ids.  Granted, in the case above it's not a problem because the two libraries are identical, but if they weren't it would be an issue.  

This solution is to 
- (a) iterate over the other library, not just the building templates to make sure all components in any tree get their id set, not just those in building templates (e.g. `ARGON` when adding BostonTemplateLib_2 to itself)
- (b) set the parent's ID to `None`, not just the traversed children - otherwise, leafs which are not used in any parents at all will fail to get their id reset (e.g. `KRYPTON` when adding BostonTemplateLib_2 to itself)

**Comment by samuelduchesne** [comment]
Makes sense! Indeed a library can have components that don't have any parents. Good catch!

**Comment by szvsw** [comment]
@samuelduchesne not yet, vpn seems to be down for me today, will try again in a bit

**Comment by szvsw** [comment]
@samuelduchesne Yeah, I opened it and it seems to open fine:

image

**Pull request merged**
