### PR TITLE
VentilationType was previously not included in dict

### PR DESCRIPTION
**Pull request by szvsw**
Very simple fix

### CODE REVIEW

**Comment by samuelduchesne** [comment]
Good catch!

**Comment by szvsw** [comment]
@samuelduchesne It looks like the setter was not set up correctly for ventilation settings (see the small changes I made)

it also looks like a bunch of other objects will fail to set Enums correctly using numbers (e.g. `ZoneConditioning.CoolingFuelType = 2`) due to the assertion statement being configured incorrectly.  Haven't gone through to fix those yet, but good to be aware of probably.

**Comment by samuelduchesne** [comment]
Yes and on top of that the setter for string or numeric was never used because the __init__ method would set an Enum directly instead of passing the property value from the constructor.

**Comment by samuelduchesne** [comment]
ZoneConditioning, ZoneLoad and WindowSettings are now fixed

**Comment by samuelduchesne** [comment]
Actually, VentilationType is not a parameter of UMI. I included it in archetypal because it is used in the workflow involving translating an IDF model into a template library. So the first commit in this PR should be reverted; But the fixes for the other enums are valid!

**Comment by szvsw** [comment]
cool, yeah, adding it to a dict was causing the tests to fail since the json libraries used in the tests don't have a ventln type key.

**Pull request merged**
